-- Drop existing tables if they exist (for development resets)
DROP TABLE IF EXISTS deliveries CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS paintings CASCADE;
DROP TABLE IF EXISTS artist_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Users table
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'buyer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Artist profiles
CREATE TABLE artist_profiles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE NOT NULL,
    bio TEXT,
    profile_picture VARCHAR(255),
    social_links JSONB,
    CONSTRAINT fk_artist_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE
);

-- Paintings
CREATE TABLE paintings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    price NUMERIC(10,2) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    status VARCHAR(20) DEFAULT 'available',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_painting_artist FOREIGN KEY (artist_id) 
        REFERENCES artist_profiles (id) ON DELETE CASCADE
);

-- Orders
CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INT NOT NULL,
    paintings_subtotal NUMERIC(10,2) NOT NULL,
    delivery_cost NUMERIC(10,2) DEFAULT 0,
    total_price NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_buyer FOREIGN KEY (buyer_id) 
        REFERENCES users (id) ON DELETE CASCADE
);

-- Order items
CREATE TABLE order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    painting_id INT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    quantity INT DEFAULT 1,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) 
        REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_painting FOREIGN KEY (painting_id) 
        REFERENCES paintings (id) ON DELETE CASCADE
);

-- Reviews
CREATE TABLE reviews (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    painting_id INT NOT NULL,
    user_id INT NOT NULL,
    rating INT NOT NULL,
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_painting FOREIGN KEY (painting_id) 
        REFERENCES paintings (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT rating_check CHECK (rating BETWEEN 1 AND 5)
);

-- Payments
CREATE TABLE payments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    transaction_id VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'initiated',
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) 
        REFERENCES orders (id) ON DELETE CASCADE
);

-- Deliveries
CREATE TABLE deliveries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    delivery_address TEXT NOT NULL,
    delivery_status VARCHAR(20) DEFAULT 'pending',
    delivery_cost NUMERIC(10,2) NOT NULL,
    courier_name VARCHAR(100),
    delivery_date TIMESTAMP,
    CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) 
        REFERENCES orders (id) ON 
        